CREATE USER loja IDENTIFIED BY bd2024
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE SEQUENCE TO loja;

-- Drop tables
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.cliente CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.estado CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.cidade CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.bairro CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.logradouro CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.cep_end CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.endereco CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.cliente_endereco CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.fabricante CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.action_figure CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.pedido CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.pedido_tem_action_figure CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.material CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.action_figure_material CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE luccagomes.imagem CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
     IF SQLCODE != -942 THEN RAISE; END IF;
END;

-- Delete from
BEGIN
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.cliente';
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.estado';
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.cidade';
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.bairro';
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.logradouro';
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.cep_end';
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.endereco';
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.cliente_endereco';
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.fabricante';
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.action_figure';
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.pedido';
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.pedido_tem_action_figure';
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.material';
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.action_figure_material';
   EXECUTE IMMEDIATE 'DELETE FROM luccagomes.imagem';
   COMMIT;
EXCEPTION
   WHEN OTHERS THEN
     IF SQLCODE != -942 THEN RAISE; END IF;
END;

BEGIN
   pr_carga_loja(1);
END;
/
COMMIT;

SELECT COUNT(*) FROM cliente;
SELECT COUNT(*) FROM estado;
SELECT COUNT(*) FROM fabricante;
SELECT COUNT(*) FROM action_figure;
SELECT COUNT(*) FROM pedido;
SELECT COUNT(*) FROM pedido_tem_action_figure;

